const fs = require("fs");
const path = require("path");
const { ethers } = require("hardhat");

// Hardhat account #1 — funded demo player used by the local web UI.
const DEMO_PLAYER_KEY = "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d";

const SEED_GAMES = [
  { key: "local|nfl|packers|bears", home: "BEARS", away: "PACKERS", heat: "GAME OF THE SEWER", homeSeed: "4200000", awaySeed: "6800000" },
  { key: "local|nfl|bills|chiefs", home: "CHIEFS", away: "BILLS", heat: "NFL", homeSeed: "4700000", awaySeed: "3100000" },
  { key: "local|mlb|cubs|brewers", home: "BREWERS", away: "CUBS", heat: "MLB", homeSeed: "800000", awaySeed: "1200000" },
];

async function main() {
  const [deployer, alice, bob] = await ethers.getSigners();
  const demoPlayer = new ethers.Wallet(DEMO_PLAYER_KEY, ethers.provider);

  const Token = await ethers.getContractFactory("TestBallToken");
  const token = await Token.deploy(ethers.parseEther("1000000000"));
  await token.waitForDeployment();
  const tokenAddress = await token.getAddress();

  const Pool = await ethers.getContractFactory("BallPool");
  const pool = await Pool.deploy(tokenAddress, deployer.address, deployer.address, 500, 200, 600);
  await pool.waitForDeployment();
  const poolAddress = await pool.getAddress();

  const fund = async (to, amount) => {
    await (await token.transfer(to, ethers.parseEther(amount))).wait();
  };

  await fund(alice.address, "50000000");
  await fund(bob.address, "50000000");
  await fund(demoPlayer.address, "25000000");

  await (await token.connect(alice).approve(poolAddress, ethers.MaxUint256)).wait();
  await (await token.connect(bob).approve(poolAddress, ethers.MaxUint256)).wait();

  const now = (await ethers.provider.getBlock("latest")).timestamp;
  const lockTime = now + 7 * 24 * 3600;
  const games = [];

  for (const [index, seed] of SEED_GAMES.entries()) {
    const externalKey = ethers.keccak256(ethers.toUtf8Bytes(seed.key));
    await (await pool.createGame(externalKey, lockTime, seed.home, seed.away)).wait();
    const gameId = index + 1;
    if (seed.homeSeed !== "0") {
      await (await pool.connect(alice).bet(gameId, 1, ethers.parseEther(seed.homeSeed), 500)).wait();
    }
    if (seed.awaySeed !== "0") {
      await (await pool.connect(bob).bet(gameId, 2, ethers.parseEther(seed.awaySeed), 500)).wait();
    }
    games.push({ id: gameId, home: seed.home, away: seed.away, heat: seed.heat, lockTime });
  }

  const network = await ethers.provider.getNetwork();
  const chainId = Number(network.chainId);
  const rpcUrl = "http://127.0.0.1:8545";

  const deployment = {
    chainId,
    rpcUrl,
    token: tokenAddress,
    pool: poolAddress,
    treasury: deployer.address,
    oracle: deployer.address,
    demoPlayer: demoPlayer.address,
    demoPrivateKey: DEMO_PLAYER_KEY,
    games,
  };

  const deploymentsDir = path.join(__dirname, "..", "deployments");
  fs.mkdirSync(deploymentsDir, { recursive: true });
  fs.writeFileSync(path.join(deploymentsDir, "local.json"), `${JSON.stringify(deployment, null, 2)}\n`);

  const webEnv = [
    "# Generated by contracts/scripts/deploy-local.js — local Hardhat demo only",
    "VITE_LOCAL_DEMO=true",
    `VITE_CHAIN_ID=${chainId}`,
    `VITE_RPC_URL=${rpcUrl}`,
    "VITE_EXPLORER_URL=",
    "VITE_APP_URL=http://localhost:5173",
    "VITE_REOWN_PROJECT_ID=",
    `VITE_POOL_ADDRESS=${poolAddress}`,
    `VITE_TOKEN_ADDRESS=${tokenAddress}`,
    "VITE_TOKEN_DECIMALS=18",
    `VITE_DEMO_PRIVATE_KEY=${DEMO_PLAYER_KEY}`,
    "",
  ].join("\n");

  const webEnvPath = path.join(__dirname, "..", "..", "web", ".env.local");
  fs.writeFileSync(webEnvPath, webEnv);

  console.log(JSON.stringify({
    ok: true,
    chainId,
    token: tokenAddress,
    pool: poolAddress,
    demoPlayer: demoPlayer.address,
    games: games.length,
    webEnv: webEnvPath,
  }, null, 2));
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
